// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCio6xYPRME_r2evnT_l1JSTJFClnoPZKA',
    appId: '1:152525618017:web:28f1be0968960bc695e320',
    messagingSenderId: '152525618017',
    projectId: 'flash-chat-ebd9f',
    authDomain: 'flash-chat-ebd9f.firebaseapp.com',
    storageBucket: 'flash-chat-ebd9f.firebasestorage.app',
    measurementId: 'G-WYHGFJBY6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjDy8Y1PDyhqNMcg_MqZ5vzgRfxv9IYfo',
    appId: '1:152525618017:android:65346d95749a708f95e320',
    messagingSenderId: '152525618017',
    projectId: 'flash-chat-ebd9f',
    storageBucket: 'flash-chat-ebd9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOam95i0QyPWc5Ha2vDpYQW6bgvn6ivrA',
    appId: '1:152525618017:ios:335f301065c6c66e95e320',
    messagingSenderId: '152525618017',
    projectId: 'flash-chat-ebd9f',
    storageBucket: 'flash-chat-ebd9f.firebasestorage.app',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOam95i0QyPWc5Ha2vDpYQW6bgvn6ivrA',
    appId: '1:152525618017:ios:335f301065c6c66e95e320',
    messagingSenderId: '152525618017',
    projectId: 'flash-chat-ebd9f',
    storageBucket: 'flash-chat-ebd9f.firebasestorage.app',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCio6xYPRME_r2evnT_l1JSTJFClnoPZKA',
    appId: '1:152525618017:web:5630dfeda5140f0f95e320',
    messagingSenderId: '152525618017',
    projectId: 'flash-chat-ebd9f',
    authDomain: 'flash-chat-ebd9f.firebaseapp.com',
    storageBucket: 'flash-chat-ebd9f.firebasestorage.app',
    measurementId: 'G-4SSBYHWFVF',
  );

}